# Generated by Django 5.0.1 on 2024-01-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CattleImageAndDiseaseDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_phone", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "image_front",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "image_back",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "image_left",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "image_right",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("doctor_advice", models.TextField(blank=True, null=True)),
                ("diagonosis", models.TextField(blank=True, null=True)),
                ("disease", models.TextField(blank=True, null=True)),
                ("treatment", models.TextField(blank=True, null=True)),
                ("approved", models.BooleanField(default=False)),
            ],
        ),
    ]
